version: '3.7'

services:
  mysql:
    image: ${IMAGE_NAME:-mysql}:${IMAGE_TAG:-latest}
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_PASSWORD
      - MYSQL_USER
    networks:
      blog-medioambiente-net:
        aliases:
          - blog-medioambiente-db
      traefik-net:
    volumes:
      - mysql-blog-medioambiente-vol:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping --silent
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      restart_policy:
        delay: ${RESTART_DELAY:-0s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}
      labels:
        traefik.enable: 'false'

networks:
  blog-medioambiente-net:
    name: ${BLOG_MEDIOAMBIENTE_NET_NAME:-blog-medioambiente-net}
    driver: overlay
    attachable: ${MYSQL_NET_ATTACHABLE:-true}
  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    external: true

volumes:
  mysql-blog-medioambiente-vol:
    name: ${MYSQL_DATA_VOLUME_NAME:-mysql-blog-medioambiente-vol}